# Start with an alpine based image with both node and kaniko installed and add other build tools as needed
FROM gperdomor/nx-kaniko:18.13.0-alpine

RUN apk add --update python3 make g++ && \
    rm -rf /var/cache/apk/*






